### PR TITLE
Change azure key vault connect method.

### PR DESCRIPTION
**Pull request by amroSaad78**
`string keyVaultEndpoint = config.GetValue<string>("KeyVaultEndpoint", null);
            if (!string.IsNullOrEmpty(keyVaultEndpoint))
            {
                var azureServiceTokenProvider = new AzureServiceTokenProvider();
                var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
                builder.AddAzureKeyVault(keyVaultEndpoint, keyVaultClient, new DefaultKeyVaultSecretManager());
            }
aaa
`

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1486) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1486) before we can accept your contribution.<br/><br/>:x: amroSaad78 [sign now](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1486)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-architecture/eShopOnContainers?pullRequest=1486) it.</sub>

**Comment by sughosneo** [comment]
Hi @amroSaad78, thank you for submitting this PR. 

Could you please provide more context on the change/PR ? 
For e.g : What's the purpose of this modification or enhancement ? Or if you have faced any issue then, how did you fix that ?
Then it would be easy for us to review and share our thoughts.

**Comment by amroSaad78** [comment]
Hi @sughosneo :
This project is very wonderful. I benefited a lot from it, but I have a suggestion to add the possibility of uploading the image of the product to Azure as the ability to download the image is present. I am also pleased to contribute to this project.
Thank you very much.

**Comment by sughosneo** [comment]
> Hi @sughosneo :
> This project is very wonderful. I benefited a lot from it, but I have a suggestion to add the possibility of uploading the image of the product to Azure as the ability to download the image is present. I am also pleased to contribute to this project.
> Thank you very much.

Hi @amroSaad78, thank you for your valuable feedback.

At this point in time, we are not planning to incorporate any extra set of features in the `eShop` application until and unless it gives a provision to explore new tools and capabilities of either related to cloud-native landscape or .NET domain. We have received many feedbacks that the `eShop` application is "too complex for a beginner". So we don't want to overwhelm anyone by adding more complexities to that.  That's the reason we won't be able to accept this feature in the mainstream development of the `eShop` application. But you could keep a separate fork of this repo under your `github account` and share the link in here for everyone to refer. You may want to update the title of the PR as well for better understanding of the feature.

Your contribution is valuable and important to us. You can pick up any other issues under the `eShopOnContainers` repo and submit a PR against that, we will be happy to review and merge the changes with the `dev` branch.

Hope that explains !

Thank you again for showing interest.

**Pull request closed without merging**
