### PR TITLE
Fixed firewall rules check and improved the script

### PR DESCRIPTION
**Pull request by EdmondShtogu**
the check shall be like ~ Get-NetFirewallRule -DisplayName eShopOnContainers-* -ErrorAction Stop

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1390) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1390) before we can accept your contribution.<br/><br/>:x: EdmondShtogu [sign now](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1390)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-architecture/eShopOnContainers?pullRequest=1390) it.</sub>

**Comment by EdmondShtogu** [comment]
@sughosneo please check

**Comment by sughosneo** [comment]
Hi @EdmondShtogu , thanks for submitting this PR. Will test and update.

**Comment by sughosneo** [comment]
Tested with both Admin and Non-Admin user. Looks good.

Thank you.

**Pull request merged**
