### PR TITLE
no more dynamics as a return types from controllers in Ordering app

### PR DESCRIPTION
**Pull request by SychevIgor**
https://github.com/dotnet-architecture/eShopOnContainers/issues/366
Without it- we can't specify response types for swagger.
also dynamic types in this case- have no benefits

@CESARDELATORRE @ramonTC @eiximenis

### CODE REVIEW

**Comment by CESARDELATORRE** [comment]
@SychevIgor We were using "dynamic" here so it is more agile if changing/adding attributes in the SQL queries in Dapper it will just be returned without needing to change any ViewModel or DTO classes for that. That is good for a single and auto-contained monolithic app. Not so good for a microservice based application where explicit "service-contracts" are more important. 
I see PROS and CONS in both approaches. We need to decide about it.
In any case, when using specific ViewModel types, have you tested it with ALL the client apps, SPA and Xamarin apps in addition to the MVC app?

**Comment by SychevIgor** [comment]
@CESARDELATORRE I did my tests with swagger ui only. My test methodology was: make a request from swagger UI, copy-paste json to jsontocshare converter and copy the result to the project. I can guarantee that json output before (with dynamic) is the same as with new strongly typed.

I did it primary, because swagger can't show us the contract(return model) before the first call as a result - you can't generate proxy based on swagger metadata. If we can't show the response model - it means that we are not using half of goods from swagger .

**Comment by SychevIgor** [comment]
Upps... I missed the fact that- MVC/SPA apps are working with updated ordering microservice without issues. It was tested. I didn't test  Xamarin, because I'm not focusing my attention on mobile part of this reference architecture

**Comment by CESARDELATORRE** [comment]
@SychevIgor 
I tested this PR with the MVC, SPA and the **Xamarin mobile app** consuming the microservices/containers.
I think that in the long term it is better to have explicit ViewModel classes (like contracts) instead dynamic ViewModels, so I merged this proposal. 
Thanks! :)

**Pull request merged**
