### PR TITLE
Fix api version for deployment

### PR DESCRIPTION
**Pull request by karoldeland**
Seems like a old version of the manifest. Corrected to use apps/v1.

### CODE REVIEW

**Comment by sughosneo** [comment]
Hi @karoldeland , thank you for submitting this PR. Will test and update.

**Comment by sughosneo** [comment]
> Hi @karoldeland , thank you for submitting this PR. Will test and update.

Hi @karoldeland , Could you please take the latest from `dev` branch and update this PR ? I could see deployment of helm chart fails with the below error, while I tried to test out this PR. 

```json
Helm Command: helm install -f app.yaml -f inf.yaml -f ingress_values_dockerk8s.yaml  --set app.name=eshop --set inf.k8s.dns=localhost  --set image.pullPolicy=Never --set inf.mesh.enabled=False --set ingress.hosts={localhost} --set inf.tls.enabled=False --name=eshop-apigwws apigwws
Error: unknown flag: --name
```
Please note `deploy-all.ps1` is already updated in `dev` branch. 

Thank you.

**Comment by karoldeland** [comment]
Sorry about that. Seems I'm not clever enough to make a pull correctly. :(

**Comment by sughosneo** [comment]
> Sorry about that. Seems I'm not clever enough to make a pull correctly. :(

No worries :)

**Pull request closed without merging**
