### PR TITLE
package actualization and some obsolete api replacement 

### PR DESCRIPTION
**Pull request by SychevIgor**
minor packages update
replace preview apis with production
replace EnableKubernetes with AddApplicationInsightsKubernetesEnricher
replace  loggerFactory.AddAzureWebAppDiagnostics(); with  loggerBuilder.AddAzureWebAppDiagnostics();

### CODE REVIEW

**Comment by SychevIgor** [comment]
https://github.com/dotnet-architecture/eShopOnContainers/issues/941

**Comment by SychevIgor** [comment]
@mvelosop hello, could you look on this PR? @CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
@eiximenis @ramonTC  - Can you review and merge this PR as part of the new push, please?

**Comment by eiximenis** [comment]
LGTM
I think we can merge this!

**Comment by mvelosop** [comment]
@eiximenis, @SychevIgor, I have a doubt about AI logging, now that we are using Serilog as the logger factory, what do you think it's better?:

- Use ApplicationInsights' sink for Serilog or
- Use ApplicationInsights' logging provider

I lean more towards using AI's sink for Serilog, to have a single logging configuration section in appsettings.

cc: @CESARDELATORRE

**Comment by SychevIgor** [comment]
@mvelosop I guess it's question for an another thread (of course, I know that you will need to merge your changes with this PR and it will throw a merge conflict :) 

General thoughts - abstraction from Azure based services- are always good idea, because all my customers wanna be free from "vendor lock". Apps Ins for them it's 100% lock.
But in another hand, based on default settings of serilog sink for app ins (excuse me if I'm wrong) https://github.com/serilog/serilog-sinks-applicationinsights
this library will filter and probably exclude some information that apps ins will log (if used directly). It's why I'm warry that it will deplete logs on App Ins and make the trace harder than now with logging directly via App Ins. As such, if you will use serilog sync- I would like to see how to configure the same depth/detail level as it's now with Application Insights direct calls

**Comment by mvelosop** [comment]
Hi @SychevIgor,

I think we should definitely start another thread about this. 

I'm not so keen in AI but I've used it in production projects and has really helped me a lot to diagnose not so obvious issues, and I've only scratched the surface but, of course, is 100% lock-in as you said.

OTOH I think logging is a fundamental tool for development, I actually use much more logging than debugging but I've found AI's latency is too high for development.

I know AI adds much more that just logging, and for sure more than I'm aware of, but the focus of the current logging branch is a bit more basic, it's on tracing process events, like the handling of integration and domain events (and also to help diagnosing posted issues 😉).

Anyway I'll merge your PR today, as it's mostly version and a few API ugrades, since there are no conflicts now. Then I'll merge my logging branch (https://github.com/dotnet-architecture/eShopOnContainers/tree/features/add-seq-sink), as I was going to have conflicts anyway, and resolve logging-related conflicts favoring Serilog's side.

Then we can begin another thread to explore AI features, integration and setup, if it's OK with you of course.

I think it'll be quite an interesting thread for everybody.

Cheers.

**Comment by mvelosop** [comment]
BTW, I've enabled AI's Serilog sink in a production environment and was also able track dependencies on AI. Just don't ask me about the setup, it just worked 😉

This could also be a topic to explore in the new thread 😊

**Pull request merged**
