### PR TITLE
VS 2017 and ASP.NET Core 2.1 enhancements 

### PR DESCRIPTION
**Pull request by rafsanulhasan**
**VS 2017** enhancements
1. Replaced bower with LibMan (PR #714)

**ASP.NET Core 2.1.3** enhancements
1. Update Identity.API, WebSPA and WebMVC projects to use ASP.NET Core 2.1.3
2. Updated NuGetPackages
3. Added HTTPS Support Identity.API, WebSPA and WebMVC Apps
4. Added HTTPS redirection to Identity.API, WebSPA and WebMVC projects
5. Added GDPR Cookie Compliance to WebMVC project
6. Formatted & Refactored coding styles and conventions

### CODE REVIEW

**Comment by CESARDELATORRE** [comment]
@rafsanulhasan - First of all, thanks a lot for your great job and amount of work for this PR.
But before moving forward, I'd like to highlight that this PR has too many features in a single PR. 

Would it be possible to split it in multiple PRs, one per feature above? We might accept some of them but not others, etc.
I.e.:
- Bower replacement should be one separated PR
- Anything related to SSL/HTTPS should be one separated PR
- Added GDPR Cookie Compliance to WebMVC project one separated PR
- ASP.NET Core version and NuGet packages in another segregated PR

Usually we accept PR's per features, but not "Formatted & Refactored coding styles and conventions" in general, but in any case, this PR should also be segregated in a single PR that can be reviewed/rejected.

Again, we really appreciate your collaboration and heelp! 👍

**Comment by rafsanulhasan** [comment]
@CESARDELATORRE, Thanks for your reply. I was also wondering that it might get difficult to to view such big PR. Could you please suggest me how to shorten an existing PR or split an existing PR into multiple? 
I found out that it might be a better way to create PRs to be merged from different branches from the forked repo.  Is that correct?

**Comment by CESARDELATORRE** [comment]
That’s right one branch per PR.
If multiple people working, the multiple forks.

**Comment by rafsanulhasan** [comment]
What about a existing PR Like this one?

**Pull request closed without merging**
