### PR TITLE
Swamy/remove unused using and refactoring entity classes

### PR DESCRIPTION
**Pull request by vishipayyallore**
1. Removed the Unused Using and Ordering.
2. Refactored the code for readability. Also moved the classes into separate files.

### CODE REVIEW

**Comment by vishipayyallore** [comment]
@sughosneo ,
Good evening. As suggested I have closed the other two PRs. Created a new one with A. Removing the unused using and reordering the usings, and B. Refactored the Code for Readability and moved the classes to separate file.

**Comment by sughosneo** [comment]
Thanks @vishipayyallore will test and update.

**Comment by vishipayyallore** [comment]
> Thanks @vishipayyallore. Will test and update.

Sumit (@sughosneo ),
Thanks for the reply. Please let me know if all is well with this PR. I will work on the next PR once this PR goes through. Many thanks.

Regards,
Swamy

**Comment by sughosneo** [comment]
Thank you @vishipayyallore for showing interest. In process of testing few of the older backlog items. Once it's done, will pick this one up.

**Pull request merged**
