### PR TITLE
Removed explicit version for Microsoft.AspNetCore.App.

### PR DESCRIPTION
**Pull request by pavinan**
Removed explicit version Microsoft.AspNetCore.App.

### CODE REVIEW

**Comment by mvelosop** [comment]
Hi @pavinan,

Why did you add the package references in the second commit?

**Comment by mvelosop** [comment]
@pavinan, what branch/commit is your repo at? 

Mine compiles just fine as of e3daacb9f63adb361776c3fc888612d5fa4ae06a in **dev**, without those references.

**Comment by pavinan** [comment]
@mvelosop, compilation fails when removed explicit version for Microsoft.AspNetCore.App. My repo is at a8b705fc in dev

**Comment by mvelosop** [comment]
Mine compiles just fine after removing the specific version.

However, mine is also a bit more recent, and in between the global.json was removed, I also have SDK 2.2.103 installed.

Would you check your's?

**Comment by pavinan** [comment]
I removed global.json and updated .net core sdk from 2.2.101 to 2.2.103. I built the project I got so many errors. See below screen shot.

image

**Comment by mvelosop** [comment]
Hi @pavinan, that might be because of previous .dll files left in obj/bin folder, I'd suggest that you remove all bin and obj folders from all projects and the rebuild the solution again, perhaps pull your repo to the latest **dev** commit, because those errors seem to be related to your installation.

**Comment by mvelosop** [comment]
Closing this PR as it seems to be a particular problem of the user installation.

**Pull request closed without merging**
