### PR TITLE
Catalog Database Seeding Issue with CatalogItem Table

### LINKED ISSUE #1350: Catalog Database Seeding Issue
After getting the latest from this project, when I am trying to run we are getting an error when seeding Catalog database

Exception: does not contain required header picturefilename

Root cause: 
In the file src\Services\Catalog\Catalog.API\Infrastructure\CatalogContextSeed.cs

In-Line 184
`string[] requiredHeaders = { "catalogtypename", "catalogbrandname", "description", "name", "price", "pictureFileName" };
                string[] optionalheaders = { "availablestock", "restockthreshold", "maxstockthreshold", "onreorder" };
                csvheaders = GetHeaders(csvFileCatalogItems, requiredHeaders, optionalheaders );`

For required headers, we are passing "pictureFileName" but in GetHeaders() when reading csv headers, we are reading headers as lowercase.

Thanks,
Pavan Kumar Aryasomayajulu

### PR DESCRIPTION
**Pull request by pavanarya**
After getting the latest from this project, when I am trying to run we are getting an error when seeding Catalog database

Exception: does not contain required header picturefilename

Root cause:
In the file src\Services\Catalog\Catalog.API\Infrastructure\CatalogContextSeed.cs

In-Line 184
string[] requiredHeaders = { "catalogtypename", "catalogbrandname", "description", "name", "price", "pictureFileName" }; string[] optionalheaders = { "availablestock", "restockthreshold", "maxstockthreshold", "onreorder" }; csvheaders = GetHeaders(csvFileCatalogItems, requiredHeaders, optionalheaders );

For required headers, we are passing "pictureFileName" but in GetHeaders() when reading csv headers, we are reading headers as lowercase.

 this commit fixes #1350 1350

Thanks,
Pavan Kumar Aryasomayajulu

### CODE REVIEW

**Comment by pavanarya** [comment]
@volkan @davidfowl @jbogard @friism I am not sure why this check webmvc  failed... Could you please let me know

**Comment by sughosneo** [comment]
Hi @pavanarya , thank you for submitting this PR and sorry for the delay in attending this.
I am not able to pull up the build related information for the WebMVC. You can close this PR and place a fresh PR for us to review and merge the changes.

**Comment by sughosneo** [comment]
> Hi @pavanarya , thank you for submitting this PR and sorry for the delay in attending this.
> I am not able to pull up the build related information for the WebMVC. You can close this PR and place a fresh PR for us to review and merge the changes.

Hi @pavanarya , just checking if you had a chance to look into this further.

**Comment by sughosneo** [comment]
Hi @pavanarya , these changes are incorporated in this PR https://github.com/dotnet-architecture/eShopOnContainers/pull/1520
So we are closing this PR as of now. 

Thank you.

**Pull request closed without merging**
