### PR TITLE
drop rudiments from identity api

### PR DESCRIPTION
**Pull request by SychevIgor**

### CODE REVIEW

**Comment by SychevIgor** [comment]
@ mvelosop maybe you also can look on this PR?

**Comment by SychevIgor** [comment]
Any feedback?

**Comment by CESARDELATORRE** [comment]
If we were going to use 2FA I guess we'd need that code, but we haven't really implemented it in eShopOnContainers...
I think I agree, please @mvelosop test that nothing breaks when removing the code from this PR (I took a look to the code and it seems safe) and then merge, when possible, ok?

Thanks @SychevIgor 👍

**Comment by mvelosop** [comment]
Hi @SychevIgor, I'm sorry I missed this completely, as @CESARDELATORRE says, this should be innocuous, will test anyway!

**Comment by mvelosop** [comment]
Everything seems ok! Thanks @SychevIgor.

**Pull request merged**
