### PR TITLE
ng5 migration

### PR DESCRIPTION
**Pull request by amihailes**
Migrate to angular 5.1.1
Adjusted some visuals
Fixed some errors
Formatted all sources to LF endline

### CODE REVIEW

**Comment by amihailes** [comment]
This is almost the same as #441 .
I solved also the problems on the orders screens and fixed some code problems.

**Comment by ramonTC** [comment]
Hi @amihailes 

Thanks for your contribution!

There are still some views that are broken though:

image

image

**Comment by amihailes** [comment]
image

**Comment by amihailes** [comment]
Hello,

I think the last push on this pull request is OK for a merge onto dev.

And you?

Regards,
Adrian

**Comment by mvelosop** [comment]
Closing this PR as it's outdated now.

**Pull request closed without merging**
