### PR TITLE
Create createresources.sh

### PR DESCRIPTION
**Pull request by vnextcoder**
Adding Bash Shell based Script for Creating Resources.

### CODE REVIEW

**Comment by vnextcoder** [comment]
Thanks @CESARDELATORRE for commit. This createresources.sh also works on Azure Cloud Bash Shell, I tested the same. I guess you would like to update Readme.MD for the same

**Comment by CESARDELATORRE** [comment]
Good point. I'll add it.
But, feel free to create a PR for documentation in the README.MD, as well. 
You might want to add a second section for the bash script. :)

**Comment by vnextcoder** [comment]
Sure. I will do.

**Comment by CESARDELATORRE** [comment]
And thanks a lot for the contribution! 👍

**Comment by vnextcoder** [comment]
#423 created

**Pull request merged**
