### PR TITLE
Feature/openshift aro

### PR DESCRIPTION
**Pull request by tmccart1**
The purpose of this pull request is to enable someone to be able to deploy this set of infrastructure and microservices to an Azure Red Hat OpenShift (ARO) cluster using Azure DevOps YAML pipelines and OpenShift YAML template files.  It contains all of the code and instructions necessary in order to get the eShopOnContainers app up and running inside of an OpenShift cluster.

Here is a [video ](https://youtu.be/NFKcEj-PKM4) explaining how all of this works with Azure DevOps and ARO :)

### CODE REVIEW

**Comment by nishanil** [comment]
@tmccart1 This is Great! Thanks for the PR. To avoid complexity and confusion, I think it will work best if you could maintain a clone of this repo and OpenShift implementation within your repo. We are happy to link your instructions and repo from our WIKI. We took a similar approach for NServiceBus implementation in the past since we couldn't maintain that implementation ourselves. Ok?

**Comment by tmccart1** [comment]
Hi @nishanil , sure that sounds great, I will definitely maintain a clone of this repo in my fork.  And thank you for linking my instructions and repo from your WIKI, that is fantastic!

**Comment by nishanil** [comment]
@mvelosop  Can you create a task to add a WIKI that links to @tmccart1 's repo for OpenShift implementation, please?

**Comment by mvelosop** [comment]
Hi @nishanil, @tmccart1, I just created a new page for [Other Deploymen Scenarios](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Other-Deployment-Scenarios) with the link.

Please @tmccart1, check if everything's OK.

Cheers,

**Comment by tmccart1** [comment]
Hi @mvelosop and @nishanil , thank you for adding that in there!  It looks pretty good, but it does have a minor typo error in it: "An example of deployment o eShopOnContainers to an..."  I am guessing you meant "to" instead of "o".  Other than that small issue, it looks great!

**Comment by mvelosop** [comment]
Fixed! 😊

**Comment by tmccart1** [comment]
Thank you, @mvelosop !!!

**Comment by tmccart1** [comment]
@mvelosop , I was actually just checking the home page of the wiki, and I noticed that that the link to the new page that you created for "Other Deployment Scenarios" is titled "Community"  Is it possible to call out OpenShift on Azure directly on that right-hand navigation of the home page?  Or title it "Other Deployment Scenarios" at least?  Community kind of throws me off, and if I was searching for OpenShift I don't think I would ever find it.  Thanks in advance!

**Comment by mvelosop** [comment]
Hi @tmccart1, you're right.

Just updated it to **Other Deployment Scenarios**.

**Pull request closed without merging**
