### PR TITLE
Swamy/04 jan2021-small-refactoring

### PR DESCRIPTION
**Pull request by vishipayyallore**

### CODE REVIEW

**Comment by vishipayyallore** [comment]
Sumit - @sughosneo 
Good afternoon. I have raised another small PR. Could you please look into this whenever you get a few minutes? Many thanks.

Regards,
Swamy

**Comment by sughosneo** [comment]
Hi @vishipayyallore , thank you for submitting this PR. Will review and update.

**Review by sughosneo — APPROVED** [review]
Review & Tested the changes with `docker-compose`. LGTM ! 
Will merge the changes with `dev` branch.

**Comment by vishipayyallore** [comment]
Sumit - @sughosneo 
Thank you so much. I will raise another PR in the next couple of days. Many thanks.

Regards,
Swamy

**Pull request merged**
